solr:
  ~
postgresql:
  # Only difference with this image is that it's more recently built from upstream's master, than upstream's image
  image: "flaxandteal/ckan-postgresql"
  postgresPassword: TEST
  # persistence:
  #   storageClassSuffix: null
redis:
  redisPassword: TEST
ckan-core:
  defaultUser:
    username: johndoe
    email: info@example.com
    password: testpassword
  plugins:
    all:
    - stats
    - text_view
    - image_view
    - recline_view
    - scheming_datasets
    - datastore
    - datapusher
    - validation
    - oauth2provider
    - harvest
    - ckan_harvester

    oauth2provider:
      secretKey: oauthkeytest

    harvest: false

    scheming: false

    validation: false
    # runOnUpdateAsync: true
    # runOnCreateAsync: true
  siteUrl: https://ckan.ev.openindustry.in
  postgres:
    password: TEST
    dataStoreRoPassword: "TEST"
  redisPassword: TEST
  plugins:
    oauth2provider:
      token: OAUTHTOKEN

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
