apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ckanProductionIni: |
    {{ include "ckanProductionIni" . }}
  ckanProductionIniWithoutPlugins: |
    {{ include "ckanProductionIniWithoutPlugins" . }}
