apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-harvester
  labels:
    app: {{ template "fullname" . }}-harvester
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    purpose: harvester
  annotations:
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      purpose: harvester
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        purpose: harvester
    spec:
      containers:
      - name: {{ template "fullname" . }}-harvester-gather
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}-env
        command:
        - "/ckan-entrypoint.sh"
        - "/usr/lib/ckan/venv/bin/python2"
        - "/usr/local/bin/ckan-paster"
        - --plugin=ckanext-harvest
        - harvester
        - gather_consumer
        - -c
        - /etc/ckan/production.ini
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_SQLALCHEMY_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_DATASTORE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-write-url
        - name: CKAN_DATASTORE_READ_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-read-url
        volumeMounts:
        - mountPath: /etc/ckan/production.ini
          name: ckan-production-ini
          subPath: production.ini
        - mountPath: /initialize.sh
          name: initialize-sh
          subPath: initialize.sh
        ports:
        - name: ckan-core
          containerPort: 5000
        resources:
{{ toYaml .Values.resources | indent 10 }}
      - name: {{ template "fullname" . }}-harvester-fetch
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}-env
        command:
        - "/ckan-entrypoint.sh"
        - "/usr/lib/ckan/venv/bin/python2"
        - "/usr/local/bin/ckan-paster"
        - --plugin=ckanext-harvest
        - harvester
        - fetch_consumer
        - -c
        - /etc/ckan/production.ini
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_SQLALCHEMY_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_DATASTORE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-write-url
        - name: CKAN_DATASTORE_READ_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-read-url
        volumeMounts:
        - mountPath: /etc/ckan/production.ini
          name: ckan-production-ini
          subPath: production.ini
        - mountPath: /initialize.sh
          name: initialize-sh
          subPath: initialize.sh
        ports:
        - name: ckan-core
          containerPort: 5000
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: ckan-production-ini
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: ckanProductionIni
            path: production.ini
      - name: initialize-sh
        configMap:
          name: {{ template "fullname" . }}-initialize
          items:
          - key: initializeSh
            path: initialize.sh
