apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-datapusher
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    purpose: datapusher
  annotations:
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
spec:
  serviceName: {{ template "fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        purpose: datapusher
    spec:
      containers:
      - name: {{ template "fullname" . }}-datapusher
        image: "{{ .Values.datapusher.image }}:{{ .Values.datapusher.imageTag }}"
        imagePullPolicy: {{ default "" .Values.datapusher.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}-env
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_SQLALCHEMY_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_DATASTORE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-write-url
        - name: CKAN_DATASTORE_READ_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-read-url
        volumeMounts:
        - mountPath: /etc/ckan/production.ini
          name: ckan-production-ini
          subPath: production.ini
        - mountPath: /initialize.sh
          name: initialize-sh
          subPath: initialize.sh
        ports:
        - name: ckan-datapusher
          containerPort: 8800
        resources:
{{ toYaml .Values.resources | indent 10 }}
