apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-post-install"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/configmap-initialize: {{ include (print $.Template.BasePath "/configmap-initialize.yaml") . | sha256sum }}
    checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-post-install"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        command: ["/ckan-entrypoint.sh", "/bin/bash", "/initialize.sh"]
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}-env
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: postgres-password
        - name: CKAN_SQLALCHEMY_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: sqlalchemy-url
        - name: CKAN_DATASTORE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-write-url
        - name: CKAN_DATASTORE_READ_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: datastore-read-url
        volumeMounts:
        - mountPath: /etc/ckan/production.ini
          name: ckan-production-ini-without-plugins
          subPath: production.ini
        volumeMounts:
        - mountPath: /etc/ckan/production-plugins.ini
          name: ckan-production-ini
          subPath: production-plugins.ini
        - mountPath: /initialize.sh
          name: initialize-sh
          subPath: initialize.sh
      volumes:
      - name: ckan-production-ini-without-plugins
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: ckanProductionIniWithoutPlugins
            path: production.ini
      - name: ckan-production-ini
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: ckanProductionIni
            path: production-plugins.ini
      - name: initialize-sh
        configMap:
          name: {{ template "fullname" . }}-initialize
          items:
          - key: initializeSh
            path: initialize.sh
