apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-env
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DATABASE_URL: {{ include "ckanSqlalchemyUrl" . | b64enc | quote }}
  CKAN_SQLALCHEMY_URL: {{ include "ckanSqlalchemyUrl" . | b64enc | quote }}
  DATASTORE_WRITE_URL: {{ include "ckanDatastoreWriteUrl" . | b64enc | quote }}
  DATASTORE_READ_URL: {{ include "ckanDatastoreReadUrl" . | b64enc | quote }}
