image: ckan/solr
imageTag: latest

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

## Persist data to a persistent volume
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  #
  ## If defined, volume.beta.kubernetes.io/storage-class: {fullname}-<storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: {fullname}-encrypted
  ##
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 8Gi
  subPath: "ckan"
